title: Precious Uche
#logo: /assets/img/headshot_circle.png
#description:Hello, I’m Precious Uche, a dedicated Data analyst skilled in transforming complex data into actionable insights. With expertise in Excel, R, and data visualization tools like Tableau and Power BI, I offer comprehensive services from data cleaning to predictive modeling. My attention to detail and client-focused approach ensures accurate, impactful results.I’m here to help you unlock your data's full potential and drive informed decisions. Let’s connect and make your data work for you. Contact me at uchepreciouschiemezie@gmail.com or +2347068637184
#show_downloads:true
theme:jekyll-theme-tactile
